"""API error models."""

from __future__ import annotations

from enum import StrEnum

from fabricgate.models.common import ApiResponseModel


class ErrorCode(StrEnum):
    """Standard error codes returned by the registry API."""

    INVALID_REQUEST = "INVALID_REQUEST"
    SCHEMA_VALIDATION_FAILED = "SCHEMA_VALIDATION_FAILED"
    DIGEST_MISMATCH = "DIGEST_MISMATCH"
    UNAUTHORIZED = "UNAUTHORIZED"
    FORBIDDEN = "FORBIDDEN"
    USER_SUSPENDED = "USER_SUSPENDED"
    NOT_FOUND = "NOT_FOUND"
    VERSION_EXISTS = "VERSION_EXISTS"
    PLATFORM_EXISTS = "PLATFORM_EXISTS"
    NAMESPACE_EXISTS = "NAMESPACE_EXISTS"
    MISSING_REQUIRED_ARTIFACT = "MISSING_REQUIRED_ARTIFACT"
    USERNAME_TAKEN = "USERNAME_TAKEN"
    RESERVED_NAMESPACE = "RESERVED_NAMESPACE"
    TOKEN_ALREADY_USED = "TOKEN_ALREADY_USED"
    INVALID_GRANT = "INVALID_GRANT"
    AUTHORIZATION_PENDING = "AUTHORIZATION_PENDING"
    SLOW_DOWN = "SLOW_DOWN"
    EXPIRED_TOKEN = "EXPIRED_TOKEN"
    AUTH_PROVIDER_UNAVAILABLE = "AUTH_PROVIDER_UNAVAILABLE"
    PAYLOAD_TOO_LARGE = "PAYLOAD_TOO_LARGE"
    UNSUPPORTED_MEDIA_TYPE = "UNSUPPORTED_MEDIA_TYPE"
    INVALID_PARAMETER = "INVALID_PARAMETER"
    INTERNAL_ERROR = "INTERNAL_ERROR"
    RATE_LIMITED = "RATE_LIMITED"
    QUOTA_FILE_TOO_LARGE = "QUOTA_FILE_TOO_LARGE"
    QUOTA_VERSION_EXCEEDED = "QUOTA_VERSION_EXCEEDED"
    QUOTA_DESIGN_EXCEEDED = "QUOTA_DESIGN_EXCEEDED"
    QUOTA_STORAGE_EXCEEDED = "QUOTA_STORAGE_EXCEEDED"
    CIRCULAR_DEPENDENCY = "CIRCULAR_DEPENDENCY"
    DEPENDENCY_NOT_FOUND = "DEPENDENCY_NOT_FOUND"
    DEPENDENCY_DEPTH_EXCEEDED = "DEPENDENCY_DEPTH_EXCEEDED"
    DEPENDENCY_COUNT_EXCEEDED = "DEPENDENCY_COUNT_EXCEEDED"
    DEPENDENCY_UNRESOLVABLE = "DEPENDENCY_UNRESOLVABLE"
    SHELL_DEPENDENCY_REQUIRED = "SHELL_DEPENDENCY_REQUIRED"
    INVALID_BITSTREAM_TYPE_FOR_FIELD = "INVALID_BITSTREAM_TYPE_FOR_FIELD"
    SHELL_NOT_FOUND = "SHELL_NOT_FOUND"
    INVALID_SHELL_BITSTREAM_TYPE = "INVALID_SHELL_BITSTREAM_TYPE"
    DEVICE_MISMATCH = "DEVICE_MISMATCH"
    BITSTREAM_TYPE_CONFLICT = "BITSTREAM_TYPE_CONFLICT"
    NOT_A_PARTIAL = "NOT_A_PARTIAL"
    MEMBER_EXISTS = "MEMBER_EXISTS"
    SOLE_OWNER = "SOLE_OWNER"
    INVALID_PERIOD = "INVALID_PERIOD"
    INVALID_DATE_RANGE = "INVALID_DATE_RANGE"
    STATS_PRIVATE = "STATS_PRIVATE"
    USER_NOT_FOUND = "USER_NOT_FOUND"
    NAMESPACE_NOT_FOUND = "NAMESPACE_NOT_FOUND"
    NAMESPACE_SUSPENDED = "NAMESPACE_SUSPENDED"
    OPERATOR_YANKED = "OPERATOR_YANKED"


class ErrorDetail(ApiResponseModel):
    """Single error detail."""

    code: str
    message: str


class ErrorResponse(ApiResponseModel):
    """Uniform error response wrapper."""

    error: ErrorDetail
